from processing_Vietnamese import Get_List_V_Sent
from processing_English import Get_List_E_Sent

paragraph = '''Representatives from more than 100 businesses operating in Viet Nam gathered today in Ho Chi Minh City for the Business Forum co-organized by the Viet Nam Chamber of Commerce and Industry (VCCI) and UNICEF. The forum served as a platform for business leaders and stakeholders to reimagine responsible business policies and practices, contributing to the achievement of child rights and in doing so contributing to the sustainable economic growth of Viet Nam. 
Madam Pham Chi Lan, Senior Economist Expert has shared her insights and delivered a lighting talk during the forum. She urged businesses to comply with the national legislations and go beyond to implement the international standards on business and human rights such as the UN Guiding Principles on Business and Human Rights and the Children’s Rights and Business Principles.
In the current context of COVID-19 pandemic, representatives from the private sector highlighted challenges and opportunities for businesses and their impact on child rights. A number of companies shared their motivation for implementing family-friendly policies and other workplace policies which represents to them a win-win solution. Many participants made a convincing case that initiatives that are good for business, are also good for parents and children, and have a positive impact on communities and the society as a whole. Some of the good examples included were breastfeeding promotion, childcare support, flexible work arrangement, parenting training, child labour prevention, maternity protection, protection and skills development of young workers with potential to scale with the wider business community. 

Apart from the unprecedented scale of COVID-19, the crisis offers us an opportunity to re-imagine and re-build systems and economies that benefit all people, including the poorest and most vulnerable. We must work together to keep economies afloat, avoid permanent damage to business operations and employment pipelines, while supporting children, families and communities through, and beyond, this global emergency. UNICEF is rallying every business – small, medium-sized or large company – to do whatever it can to anticipate and mitigate negative impacts on children, as children are everyone’s business. 

The forum today highlighted the good initiatives and models and called for more collaborations among stakeholders to go beyond compliance and focus on sustainability of business actions. Lots of benefits can be easily foreseen if businesses invest in those policies, such as improvement in workers’ productivity and performance, promotion of corporate culture, reputation, public image and brand value which all lead to boosted profitability. 

In order to ensure the strategic economic development, it is necessary to be responsible and sustainable business. It means business operation has to bring benefit to everyone including children, ensure the closed-reasonable-harmonise combination among economic efficiency with social responsibility, natural resource and environment protection. We would like to call for the collaboration among different stakeholders to promote Child Rights and Business Principles (CRBP) to reimagine the model of responsible business, with socially responsible policies and practices are part of the company’s DNA.

With technical support and facilitation from Management and Sustainable Development Institute (MSD), participants and panelists also discussed how to build back better through child-friendly 
business strategy in order to protect and promote child rights through products and services and community development projects/interventions. A travel and tourism company shared how it has integrated child protection issues in its code of conduct and partner training. One of the largest local footwear manufacturers highlighted the company’s long-term investment in the community to provide clean water. The discussion also highlighted the importance of building partnerships between Business – Social Organization and Public-Private Partnership. 
Child Rights and Business Principles help business invest in the children and youth wisely and strategically to ensure their economic growth and sustainable development. In the process of promoting Child Rights in business, business should partner with social organizations as they are close to children and youth and have rich expertise and experience in promoting and ensuring Child Rights. The partnership can create more shared value to both partners and especially to children and youth.'''

print(Get_List_E_Sent(paragraph))